import api from './axios'
export const getConfig          = ()         => api.get('/api/admin/config')
export const updateConfig       = (data)     => api.put('/api/admin/config', data)
export const getUnknownFaces    = (params)   => api.get('/api/admin/unknown-faces', { params })
export const getUnknownStats    = ()         => api.get('/api/admin/unknown-faces/stats')
export const assignUnknownFace  = (id, userId) => api.post(`/api/admin/unknown-faces/${id}/assign`, { user_id: userId })
export const deleteUnknownFace  = (id)       => api.delete(`/api/admin/unknown-faces/${id}`)
export const bulkDeleteUnknown  = (ids)      => api.delete('/api/admin/unknown-faces/bulk-delete', { data: { ids } })
export const deleteAllUnknown   = ()         => api.delete('/api/admin/unknown-faces/bulk-delete', { data: { all: true } })
export const cleanupUnknown     = ()         => api.post('/api/admin/unknown-faces/cleanup')
export const reloadCache        = ()         => api.post('/api/admin/reload-cache')
export const getSystemInfo      = ()         => api.get('/api/admin/system-info')
export const getDbHealth        = ()         => api.get('/api/admin/db-health')
export const getStorageInfo     = ()         => api.get('/api/admin/storage/info')
export const cleanupStorage     = ()         => api.post('/api/admin/storage/cleanup')
export const compressStorage    = ()         => api.post('/api/admin/storage/compress')

